add Ethernet support for iMX6ULL EVK
ms-iot/imx-edk2-platforms pull request #32
Opened 2019-05-21 04:46 UTC by DachunRao

2019-05-21 19:55 UTC, hbeberman approved these changes

2019-05-22 04:09 UTC, christopherco requested changes

2019-05-22 04:09 UTC, christopherco commented on Platform/NXP/iMX6ULL_EVK_512MB/AcpiTables/Dsdt-Enet.asl
> +/*
Add doxygen-style header
```suggestion
/** @file
```

2019-05-22 04:09 UTC, christopherco commented on Platform/NXP/iMX6ULL_EVK_512MB/AcpiTables/Dsdt-Enet.asl
> +*  Copyright (c) Microsoft Corporation. All rights reserved.
Add year to copyright
```suggestion
*  Copyright (c) 2019 Microsoft Corporation. All rights reserved.
```

2019-05-22 04:09 UTC, christopherco commented on Platform/NXP/iMX6ULL_EVK_512MB/Library/iMX6BoardLib/iMX6BoardInit.c
> +  // Enable ENET PLL
Are these ENET settings already configured in U-Boot? If so, it would be cleaner to remove this init code and rely on U-Boot's configuration.

2019-05-22 04:09 UTC, christopherco commented on Silicon/NXP/iMX6Pkg/Include/iMX6_ULL.h
> +    unsigned  Zero2 : 9;                 // 22-30
Nit - Align comment
```suggestion
    unsigned  Zero2 : 9;                  // 22-30
```

2019-05-22 08:15 UTC, christopherco approved these changes

2019-05-22 08:17 UTC, merged