Addresses TianoCore review comments for "Silicon/NXP: Add i.MX6 ACPI tables" Patch
ms-iot/imx-edk2-platforms pull request #4
Opened 2019-01-09 02:44 UTC by christopherco

This patch addresses upstream reviewer comments to the i.MX6Pkg ACPI tables patch.

Original TianoCore upstream review comments: https://lists.01.org/pipermail/edk2-devel/2018-December/034101.html

2019-01-09 18:59 UTC, jordanrh1 commented on Silicon/NXP/iMX6Pkg/AcpiTables/Dsdt-Enet.asl
> +  Name (_CCA, 1)  // ENET is cache coherent
>Name (_CCA, 1)  // ENET is cache coherent [](start = 2, length = 41)

What does this mean - is it used by the miniport or NDIS?

2019-01-09 19:15 UTC, jordanrh1 commented on Silicon/NXP/iMX6Pkg/AcpiTables/Dsdt-Enet.asl
> +  Name (_CCA, 1)  // ENET is cache coherent
I think what this means, is if the device is cache coherent, a CPU that accesses memory which has just been written by the device does NOT need to invalidate it's cache for that memory region before accessing that memory. It is my understanding that ARM is not generally cache coherent, and the CPU must invalidate it's cache before accessing that memory. Are you certain that a cache invalidation is not required?

---
In reply to: [246500631](https://github.com/ms-iot/imx-edk2-platforms/pull/4#discussion_r246500631) [](ancestors = 246500631)

2019-01-09 19:18 UTC, jordanrh1 requested changes
Need to be certain that _CCA=1 is correct. _CCA=0 is the safer option, since the CPU will perform cache invalidations and flushes on memory it shares with devices.

It looks like the system queries this property but I'm not seeing it used in any device stacks. I suspect that testing both ways will work.

2019-01-09 21:28 UTC, neilsh-msft commented on Silicon/NXP/iMX6Pkg/AcpiTables/Dbg2.aslc
> -#include "iMX6.h"
These should be sorted alphabetically?  Above you have <imx6.h> followed by <platform.h>, here you have it reversed.

2019-01-09 22:21 UTC, neilsh-msft commented
For Jordan's _CCA comments, I know on the iMX8 platform I have to use _CCA set to zero for the SDHC controller.

2019-01-09 22:43 UTC, christopherco commented
Regarding _CCA, I do agree _CCA=0 is the safer option.

My conundrum is that Windows default behavior is cache-coherent access. On x86/amd64, which is what the inbox driver stacks were initially targeted towards, accesses are cache coherent. _CCA was only recently added in ACPI 6.0+ to handle ARM's inconsistent cache-coherency policies. Since the Windows policy was initially based on x86/amd64 policy, the absence of _CCA implies _CCA=1.

That being said, I see no functional harm in changing _CCA to 0 for these. It would be a (probably minor) perf hit but it is the safer option.

2019-01-09 22:47 UTC, christopherco commented
Correction: My above comment was only true for ARM64. HAL enforces that the absence of _CCA implies _CCA=0 on ARM32. Will change

2019-01-09 22:52 UTC, christopherco commented on Silicon/NXP/iMX6Pkg/AcpiTables/Dbg2.aslc
> -#include "iMX6.h"
This was an oversight. Will fix.

2019-01-10 18:35 UTC, jordanrh1 approved these changes

2019-01-10 18:46 UTC, neilsh-msft approved these changes

2019-01-10 18:56 UTC, merged